# -*- coding: utf-8 -*-
import sys
from sbimt.sbimt import SBIMT
from sbimt.user import User
import argparse


def parse_args():
    parser = argparse.ArgumentParser(description='Taking a test to translate, \
                                     its reference file, the Moses init file \
                                     of a trained system and an HMM alignment \
                                     model; this software simulates a user \
                                     working on a segment-based IMT \
                                     framework.')
    parser.add_argument('-s', '--sources', metavar='source_file',
                        required=True, help='file containing the source \
                        segments.')
    parser.add_argument('-r', '--references', metavar='reference_file',
                        required=True, help='file containing the reference\
                        segments.')
    parser.add_argument('-c', '--config', metavar='moses_ini',
                        required=True, help='file containing moses\
                        configuration.')
    parser.add_argument('-a', '--alignments', metavar='alignments_file',
                        required=True, help='file containing the alignments\
                        generated by alignments.sh')
    parser.add_argument('-v', '--verbose', default=False,
                        action='store_true', required=False, help='Activate \
                        verbose mode.')
    parser.add_argument('-x', '--xml', default=False,
                        action='store_true', required=False, help='Show \
                        XML markup.')
    parser.add_argument('-p', '--probability', metavar='threshold',
                        required=False, type=float, help='probability \
                        threshold. (Default 0.)', default=0)
    parser.add_argument('-t', '--confidence', metavar='threshold',
                        required=False, type=float, help='condidence \
                        threshold. (Default 0.)', default=0)
    parser.add_argument('-l', '--level', metavar='[1-3]',
                        required=False, type=int, help='what to use CM for: \
                        1- use CM to validate segments. 2- use CM to \
                        correct words. 3- use CM to both validate and \
                        correct.\n(Default 3.)', default=3,
                        choices=range(1, 4))
    parser.add_argument('-m', '--moses', metavar='moses_bin',
                        required=False, default='/opt/moses/bin/moses',
                        help='Path to moses bin. (Default: \
                        /opt/moses/bin/moses.)')

    return parser.parse_args()


if __name__ == "__main__":
    """
    Start of the simulation.
    """

    # Check arguments.
    args = parse_args()

    # Session set-up.
    sys.stderr.write("\x1b[2J\x1b[H")
    sys.stderr.write('Preparing systems  (it may take a while)...\n')
    session = SBIMT(args.config, args.alignments, args.probability,
                    args.confidence)
    reference_file = open(args.references, 'r')
    translation_file = open('test.hyp', 'w')
    total_sentences = 0
    for s in open(args.sources):
        total_sentences += 1
    current_sentence = 1

    # IMT session (sentence by sentence).
    for source in open(args.sources):

        # Data initialization.
        reference = reference_file.readline().strip().split()
        sim = User(reference)

        # Show progess.
        sys.stderr.write("\x1b[2J\x1b[H")
        sys.stderr.write('Progress: ' + str(current_sentence) + '/'
                         + str(total_sentences) + ' [' + "{0:.2f}".format(
                             current_sentence / float(total_sentences) * 100)
                         + ' %]\n')
        current_sentence += 1

        # Session initialization.
        session.newSentence(source.split())
        validated_translation = False

        if args.verbose:
            print('SOURCE: ' + source.strip())
            print('REFERENCE: ' + ' '.join(reference))

        # Iterative process.
        while not validated_translation:

            # Load new hypothesis.
            session.newHypothesis()

            if args.verbose:
                print('TRANSLATION:', session.getTranslation())

            # Check if new hypothesis is the desired translation.
            if session.getTranslation() == ' '.join(reference):
                session.validateTranslation()
                validated_translation = True
                continue

            # Segment Validation.
            if args.level == 1 or args.level == 3:
                segment_validated = sim.validateSegmentsCM(session)
            else:
                segment_validated = sim.validateSegments(session)

            # Word Correction / Sentence Validation.
            if args.level == 2 or args.level == 3:
                new_word = 'Ò.Ó'
                while new_word == 'Ò.Ó':
                    new_word = sim.wordCorrectionCM(session)
            else:
                new_word = sim.wordCorrection(session)

            if new_word == '':  # and not segment_validated:
                session.validateTranslation()
                if args.verbose:
                    print('')
                    print('')
                    print('CORRECTED WORD: ')
                    print('WORD SEGMENTS:', session.getWordSegments())
                    print('DELETED WORDS:', session.getDeletedWords())
                    print('')
                validated_translation = True
                continue

            # XML Generation.
            session.generateXML()

            if args.verbose:
                print('')
                print('')
                print('CORRECTED WORD:',  new_word)
                print('WORD SEGMENTS:', session.getWordSegments())
                print('DELETED WORDS:', session.getDeletedWords())
                print('')
                if args.xml:
                    print('XML:', session.getXML())

        if args.verbose:
            print('')
            print('Word Strokes: ', session.getWordStrokes())
            print('Mouse Actions:', session.getMouseActions())

            print("-----------------------------------------")
            print('')

        translation_file.write(session.getValidatedTranslation() + '\n')

    # Show metrics.
    print('WSR:', "{0:.1f}".format(session.getWSR()))
    print('MAR:', "{0:.1f}".format(session.getMAR()))
    print('WDR:', "{0:.1f}".format(session.getWDR()))
    translation_file.close()
